package support;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import util.DBUtil;

/**
 * DAOの特性テスト用に、埋め込みH2(jdbc:h2:mem:...)へ接続先を切り替え、
 * 本番相当のスキーマを用意するヘルパー。
 *
 * 本番コードにはMUTTERSテーブルの作成スクリプトが存在しない
 * (USERS/FOLLOWS/MUTTER_LIKESは各DAOのensureSchema()で作成されるが、
 *  MUTTERSは手動で作られている前提と推測される)。
 * そのため、既存コード(MutterDAO/MutterInputValidator/createAndReturnの
 * RETURN_GENERATED_KEYS利用)から逆算した定義をここに明記する。
 * 実データベースの実際の定義と差異がないか、Phase2でのFlywayベースライン化の際に
 * 必ず突き合わせて確認すること。
 *
 * (モダナイゼーション計画 Phase0: 安全網構築)
 */
public final class TestDatabaseSupport {
    private TestDatabaseSupport() {
    }

    /**
     * 呼び出しごとに独立した埋め込みH2を用意し、DBUtilの接続先を切り替える。
     * DB_CLOSE_DELAY=-1 は、DAOがコネクションプールを使わず毎回接続を閉じる実装のため、
     * 最初の接続が閉じた時点でDBが消えてしまわないようにするために必要。
     */
    public static void useFreshInMemoryDatabase(String dbName) {
        System.setProperty("db.url", "jdbc:h2:mem:" + dbName + ";DB_CLOSE_DELAY=-1");
        System.setProperty("db.user", "sa");
        System.setProperty("db.password", "");
        createSchema();
    }

    /** 各テストの前に呼び、テーブルの中身だけを空にする(スキーマは再作成しない)。 */
    public static void clearAllTables() {
        try (Connection conn = DBUtil.getConnection();
                Statement stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM MUTTER_LIKES");
            stmt.execute("DELETE FROM FOLLOWS");
            stmt.execute("DELETE FROM MUTTERS");
            stmt.execute("DELETE FROM USERS");
            stmt.execute("ALTER TABLE USERS ALTER COLUMN ID RESTART WITH 1");
            stmt.execute("ALTER TABLE MUTTERS ALTER COLUMN ID RESTART WITH 1");
        } catch (SQLException e) {
            throw new RuntimeException("テスト用テーブルの初期化に失敗しました。", e);
        }
    }

    private static void createSchema() {
        try (Connection conn = DBUtil.getConnection();
                Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS USERS ("
                    + "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "NAME VARCHAR(100) NOT NULL UNIQUE, "
                    + "PASS VARCHAR(100) NOT NULL, "
                    + "BIO VARCHAR(255) DEFAULT '' NOT NULL)");

            // 推測スキーマ: 本番のMUTTERS定義未確認のため要突き合わせ(クラスコメント参照)
            stmt.execute("CREATE TABLE IF NOT EXISTS MUTTERS ("
                    + "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "USER_ID INT NOT NULL, "
                    + "TEXT VARCHAR(255) NOT NULL, "
                    + "VERSION INT NOT NULL DEFAULT 0, "
                    + "CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)");

            stmt.execute("CREATE TABLE IF NOT EXISTS MUTTER_LIKES ("
                    + "ID INT AUTO_INCREMENT PRIMARY KEY, "
                    + "MUTTER_ID INT NOT NULL, "
                    + "USER_ID INT NOT NULL, "
                    + "CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "
                    + "UNIQUE(MUTTER_ID, USER_ID))");

            stmt.execute("CREATE TABLE IF NOT EXISTS FOLLOWS ("
                    + "ID INT AUTO_INCREMENT PRIMARY KEY, "
                    + "FOLLOWER_ID INT NOT NULL, "
                    + "FOLLOWEE_ID INT NOT NULL, "
                    + "CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "
                    + "UNIQUE(FOLLOWER_ID, FOLLOWEE_ID))");
        } catch (SQLException e) {
            throw new RuntimeException("テスト用スキーマの作成に失敗しました。", e);
        }
    }
}
