-- 全ての件数が0なら、PostgreSQLの外部キーとNOT NULL制約を安全に追加できる。
SELECT 'MUTTERS without USERS' AS CHECK_NAME, COUNT(*) AS INVALID_COUNT
FROM MUTTERS m LEFT JOIN USERS u ON u.ID = m.USER_ID
WHERE u.ID IS NULL;

SELECT 'MUTTER_LIKES without MUTTERS' AS CHECK_NAME, COUNT(*) AS INVALID_COUNT
FROM MUTTER_LIKES ml LEFT JOIN MUTTERS m ON m.ID = ml.MUTTER_ID
WHERE m.ID IS NULL;

SELECT 'MUTTER_LIKES without USERS' AS CHECK_NAME, COUNT(*) AS INVALID_COUNT
FROM MUTTER_LIKES ml LEFT JOIN USERS u ON u.ID = ml.USER_ID
WHERE u.ID IS NULL;

SELECT 'FOLLOWS without FOLLOWER' AS CHECK_NAME, COUNT(*) AS INVALID_COUNT
FROM FOLLOWS f LEFT JOIN USERS u ON u.ID = f.FOLLOWER_ID
WHERE u.ID IS NULL;

SELECT 'FOLLOWS without FOLLOWEE' AS CHECK_NAME, COUNT(*) AS INVALID_COUNT
FROM FOLLOWS f LEFT JOIN USERS u ON u.ID = f.FOLLOWEE_ID
WHERE u.ID IS NULL;

SELECT 'MUTTER_LIKES null CREATED_AT' AS CHECK_NAME, COUNT(*) AS INVALID_COUNT
FROM MUTTER_LIKES WHERE CREATED_AT IS NULL;

SELECT 'FOLLOWS null CREATED_AT' AS CHECK_NAME, COUNT(*) AS INVALID_COUNT
FROM FOLLOWS WHERE CREATED_AT IS NULL;
