CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    pass VARCHAR(255) NOT NULL,
    bio VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE mutters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    text VARCHAR(255) NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mutters_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_mutters_id_desc ON mutters (id DESC);

CREATE TABLE mutter_likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mutter_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_mutter_likes_mutter_user UNIQUE (mutter_id, user_id),
    CONSTRAINT fk_mutter_likes_mutter
        FOREIGN KEY (mutter_id) REFERENCES mutters (id) ON DELETE CASCADE,
    CONSTRAINT fk_mutter_likes_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE follows (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id INTEGER NOT NULL,
    followee_id INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_follows_follower_followee UNIQUE (follower_id, followee_id),
    CONSTRAINT fk_follows_follower
        FOREIGN KEY (follower_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_follows_followee
        FOREIGN KEY (followee_id) REFERENCES users (id) ON DELETE CASCADE
);
